# Many parts of this file are taken from https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/
baseURL = "https://tyomaiva.github.io"
Title = "Artem's notes on computer technologies and education"
theme = "refined"

[Author]
  name = "Artem Ivashko"

[Social]
  github = "tyomaiva"

[Params]
  tagline = "Заметки Артёма о компьютерных технологиях и образовании"
  mainSections = ["posts"]
  html5_validator = true
  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons = false

  themecolorbase = "brown"

  [Params.source]
    url = "https://github.com/tyomaiva/tyomaiva.github.io"
    org_dir = "content-org"
    md_dir = "content"
    ox_hugo = true

  [[Params.social]]
    name = "Github"
    link = "https://github.com/tyomaiva/"
    relme = true

[markup.goldmark.renderer]
  unsafe = true


[Taxonomies] # [indexes] is obsolete since v0.11
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"
  series = "series"
