theme = "minimal"

[[menu.main]]
    url = "/"
    name = "Домашняя"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Блог"
    weight = 3

[[menu.icon]]
    url = "https://????"
    name = "facebook"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true
