#+options: H:5
#+options: creator:t
#+seq_todo: TODO DRAFT DONE
#+property: header-args :eval never-export

#+AUTHOR: Artem Ivashko
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
* Blog Ideas
** DONE Михаил Семёнович Якир: по страницам учебников Мерзляка и Ко :@education:mathematics:
   CLOSED: [2020-10-14 Wed 16:46]
   :PROPERTIES:
   :EXPORT_FILE_NAME: Yakir
   :END:
#+BEGIN_EXPORT html
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v8.0" nonce="DkNGMnnm"></script>
#+END_EXPORT
#+BEGIN_QUOTE
или "Математика после окончания школы vs. реальная жизнь"
#+END_QUOTE
*** Мотивация и предыстория
Лет около 20 назад я начал учиться в классе замечательного учителя математики, [[https://ru.wikipedia.org/wiki/%D0%AF%D0%BA%D0%B8%D1%80,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%B8%D1%87][Михаила Семёновича Якира]]. И вот я случайно наткнулся на его канал в Youtube под названием [[https://www.youtube.com/channel/UCMNZdL8EWKoHHMxzcMiFR_A]["Математика. По страницам учебников Мерзляка и Ко"]], который Михаил Семёнович (далее сокращенно М. С.) начал вести совсем недавно.

Если честно, вышеупомянутый канал, как выход М. С. в медиа-пространство, был для меня неожиданностью. Но видимо, это тот случай, когда молчать нельзя. Дело в том, что мой учитель вышел на пенсию несколько лет назад, и в силу обстоятельств преподавать в школе не может. Тем более вся эта ситуация с вирусом. А поделиться "вживую" есть чем: 40 лет педагогического опыта на дороге не валяются. И вот, в качестве отклика на появление канала, я спонтанно решил подготовил текст, что Вы видите сейчас перед глазами. Я никогда раньше не вёл блога, а привык общаться лично, так что этот жанр для меня новый. Но просто добавить комментарий к какому-то из видеороликов было бы явно недостаточно, а завести блог в 2020 году так же легко, как сходить в супермаркет за продуктами. (Правда, на деле всё оказалось несколько сложнее, но не суть важно.)

Целей у этой заметки несколько:
+ набросать штрихи к учебному подходу М. С., исходя из собственных воспоминаний,
+ отрефлексировать роль школьной математики в жизни взрослого человека, особенно не-математика,
+ проявить благодарность своему учителю.
О первых двух темах можно (и стоит) говорить долго, здесь же я буду касаться их поверхностно. В качестве дополнительных иллюстраций буду использовать ролики на вышеназванном канале.


Как ни странно, первый вопрос, который встал перед написанием настоящей заметки, был о языке. С одной стороны, со своими домочадцами я разговариваю виключно українською мовою (ні, не думайте, що це зумовлено модою або політичною ситуацією, так було заведено в нас вже останні 10 років). С другой стороны, с окружением я разговариваю в основном на английском (вперемешку с ломаным голландским). С третьей стороны, я вырос в русскоязычной семье. Но поскольку сам М. С. общается по-русски, в том числе на своём канале, я решил избрать последний вариант. Надеюсь, это решение не оттолкнёт потенциальных читателей блога и зрителей канала. Для меня язык -- это средство для соединения, а не повод для разделения.

Для контекста, скажу несколько слов о личном школьном пути. Последние четыре класса (с 8 по 11) я учился в киевском лицее со скромным названием "[[https://uk.wikipedia.org/wiki/%D0%9A%D0%B8%D1%94%D0%B2%D0%BE-%D0%9F%D0%B5%D1%87%D0%B5%D1%80%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D0%BB%D1%96%D1%86%D0%B5%D0%B9_%E2%84%96_171_%C2%AB%D0%9B%D1%96%D0%B4%D0%B5%D1%80%C2%BB][Лидер]]", в классе с углублённым изучением математики ("матклассе"). Лично я считаю этот лицей одним из лучших мест по /всей/ Украине для обучения математике вообще и подготовки к математическим соревнованиям ("олимпиадам") в частности. (Так было в моё время, по крайней мере. Да, я осознаю эффект жабы хвалящей своё болото, но при необходимости могу предоставить объективные метрики.) Так сложилось благодаря многолетнему упорному труду М. С. и его коллег [[https://www.litres.ru/vitaliy-polonskiy/ob-avtore/][Виталия Борисовича Полонского]] и Аркадия Григорьевича Мерзляка (впрочем, о последнем я знаю скорее понаслышке, непосредственного контакта с ним я не имел). Что интересно, по слухам, некоторые из выпускников лидеровского маткласса сами пошли по преподавательской стезе и впоследствии начали составлять серъёзную конкуренцию самому М. С. в плане подготовке олимпиадников. Что не может не служить неявным комплиментом их alma mater.

*** Чему нас учили (и зачем?)
А точнее -- что нам прививали? Попробую рассказать без излишней ностальгии.

Первое -- это "математическая культура". Чтобы понять, о чём идёт речь, настоятельно рекомендую просмотреть видео [[https://www.youtube.com/watch?v=di_iuy1heJY]["90% учащихся решают эти задачи НЕПРАВИЛЬНО"]] перед тем, как читать дальше. По-моему, М. С. ни в этом ролике, ни в других, не использует термина "математическая культура", хотя в школе он орудовал им постоянно. По сути, под этим термином подразумевается умение решить задачу до конца, не упуская деталей или каких-то частных случаев. Очевидно, что без этого навыка занятия математикой вырождаются в следование какой-то квази-науке, где большинство утверждений до конца не доказаны, а значит и потенциально неверны.

Но какой тогда толк от такой культуры в реальной взрослой жизни? Не проявление ли это какой-то нездоровой дотошности и перфекционизма? По своему опыту скажу, что на практике в физике утверждения часто не доказываются математически строго, хотя математики там полно, причём на любой вкус. Там намного важнее предоставить /убедительную/ цепочку рассуждений. Куда уж тут до культуры?

По-моему, суть культуры заключается не в математической строгости как таковой, а в навыке целостного анализа ситуации и выявлении потенциальных "краевых случаев" (edge cases). Например, производится какая-то операция, которая в краевом случае вообще неопределена, и такой сценарий сразу детектируется в уме. Часто выявление краевого случая и вывод о его важности делается очень быстро, почти подсознательно, и в случае неважности даже не проговаривается, но тем не менее такой процесс /крайне/ важен. Предупреждён -- значит вооружён. Банальный пример из программирования -- [[https://en.wikipedia.org/wiki/Buffer_overflow][buffer overflow]], когда в массив фиксированного размера добавляются и убираются элементы, но не учитывается случай, когда добавить новый элемент уже некуда. И честный компьютер добавляет этот элемент в ту область памяти, где содержится уже другой объект. Ба-бах! Как ни банально звучит этот сценарий, он до сих пор очень "популярен" в программных продуктах и в прошлом дал почву для использования хакерами. Одной из причин того, что такие вещи "проходят", является трудноуловимость такого сценария при тестировании, и если даже программист его упустил, шансы велики, что разработчик тестов последует его примеру. Вывод -- такие случаи нужно продумывать в голове сразу, во время написания кода.

Второе -- понятие о математической красоте. Опять для иллюстрации приведу видео с того же канала: [[https://www.youtube.com/watch?v=m4jH_VcjoEM]["Что такое Красивая задача, или когда на плоскости места мало".]] Но постойте, какая может быть красота в /математике/? Не является ли это очередным злоупотреблением общего понятия? Ведь красота бывает в живописи, в музыке, и вообще само слово попахивает метафизикой. Что интересно, после многолетних рассуждений я сам не могу дать удовлетворительное определение красоты. Но вот какое интересное определение даёт М. С. в этом ролике:
#+BEGIN_QUOTE
Красивая задача = Простота + Неожиданность.
#+END_QUOTE
Неожиданность решения задачи. Простота как решения, так и самой постановки задачи. Для иллюстрации этой "формулы" М. С. приводит задачу, которую я видел впервые, но решение которой меня просто потрясло. (Михаил Семёнович, почему Вы нам её не давали?! Или я тогда болел?:-) Опять-таки, всем советую просмотреть видеоролик.

Со своей стороны могу привести пример красивой задачи, которая запомнилась со школьной скамьи:
#+BEGIN_QUOTE
Cуществует ли равносторонний треугольник с вершинами в узлах плоской квадратной сетки?
#+END_QUOTE
(То есть, представьте себе листочек тетрадки в клеточку, только бесконечный в обоих измерениях, и Вы можете выбирать любые три точки в углах квадратиков.) Согласитесь, формулировка -- чрезвычайно простая. Решений, наверное, существует несколько, но то, которое мне известно -- и элегантное, и неожиданное. Впрочем, не буду его здесь выкладывать, попробуйте подступиться к нему сами. Если не выйдет, мы что-то придумаем в комментариях. Кроме того, заметьте, что в этой задаче присутствует азарт -- ведь ответа на поставленный вопрос может быть два ("да" и "нет"), и для начала решения нужно выбрать один из них в качестве гипотезы, но какой?

В "нестандартных" задачах (М. С. использует именно такой термин, а не "олимпиадные" задачи) подобной красоты -- полно. Можно даже сказать, что неожиданность -- /непременный атрибут/ нестандартной задачи (иначе она превращается в обыкновенную). Таких задач мы решали много, и в школе, и за её пределами. Добрая четверть класса ими жила (без фанатизма, впрочем). М. С. регулярно готовил нам так называемые "задавальники" -- блоки по 5-10 задач, которые можно было решать в течение нескольких недель. Тот факт, что они формулировались просто, позволял их легко запоминать и решать где угодно -- в классе, дома на диване, в автобусе, в дýше, или даже на ходу. Что интересно, те задавальники до сих пор хранятся у меня дома в Киеве. Вообще, я старался сохранить задачи со /всех/ соревнований, в которых я учавствовал, по математике так точно. Если новое поколение учащихся/учителей в этом заинтересовано, обращайтесь, что-нибудь придумаем.

Хочу заметить, что иногда такие нестандартные задачи получается-таки решить по-стандартному, методом грубой силы. Решение тогда часто выходит очень громоздким, скучным, не прослеживается какая-то особенная идея решения (метод ведь стандартный). Как следствие, в ходе формальных преобразований решающий может вполне пропустить ошибку (например, упустить частный случай), в порыве выдать желаемое за действительное. Такие случаи М. С. характеризовал выражением "убить задачу". Например, не искать решение геометрической задачи, требующей всего нескольких дополнительных построений, а решить её в лоб методом координат на три-четыре страницы выкладок. (Представьте себе лицо человека, проверяющего такую задачу.) Другой способ "убить задачу" -- применить "запрещённые" методы, выходящие за рамки школьной программы. Помню, как М. С. возмущался, когда услышал о решении одной задачи на олимпиаде с помощью приближения синуса несколькими первыми членами его ряда Тейлора. Если цель -- это просто уметь решать задачи любой ценой, то ладно. Но наш учитель смотрел дальше. Позже я и сам убедился, что забегание вперёд часто ни к чему хорошему не приводит.

Кроме технических навыков и углубления знаний, я думаю, что мы приобрели "вкус", как некий побочный эффект от решения красивых задач. Как и красота, вкус тяжело поддаётся определению, но тем не менее он объективно существует. Вкус, позволяющий выбрать адекватный подход к решению задачи, и отсеять неадекватный. Вкус к самому выбору задач.

Опять выйдем за школьные рамки. Зачем нам искать простоту и зачем тут какой-то вкус? Возьмём инженерию, понимаемую в широком смысле, как построение систем прямой практической ценности из большого количества заранее хорошо изученных ингридиентов. Так вот, в дальновидной инженерии давно признано, что чем проще дизайн, тем лучше. Почему? Эстетика мало интересует большинство инженеров, и тем более руководителей проектов и заказчиков. Но как ни банально, чем меньше частей, тем меньше причин поломки или непредсказуемого поведения системы. Тем легче удерживать в голове всю систему и анализировать взаимодействие её частей. Тем качественнее полученный продукт. (Кому интересно, смотрите [[https://en.wikipedia.org/wiki/KISS_principle][принцип KISS]], а применении к программированию -- [[https://www.infoq.com/presentations/Simple-Made-Easy/][Simple Made Easy]].)

Что касается выбора задач, мне лично время от времени попадаются "извращённые" задачи, или такие задачи, где кто-то давно уже выбрал за меня метод решения (а времени перекроить уже просто нет), или где другие части системы не дают свободы. Что же, в таком случае нужно просто решать задачу, а вкус временно отключить. Но там, где пути решения открыты (чаще всего, это касается новых проектов), вкус играет неоценимую роль путеводителя.

*** Заключение
Я очень признателен Михаилу Семёновичу за все усилия, которые он вложил для того, чтобы помочь мне полюбить математику и научиться мыслить за рамками стандартов, в частности, решать нестандартные математические задачи. При том, что я не показывал особенных результатов, в отличие от других одноклассников, например, [[https://imo-official.org/participant_r.aspx?id=7940][Васи Кузнецова]], [[https://imo-official.org/participant_r.aspx?id=8434][Саши Кравца]], [[https://stats.ioinformatics.org/people/2601][Юры Зновьяка]], [[https://stats.ioinformatics.org/people/552][Данила Мысака]], и некоторых других. Оглядываясь назад, нельзя не признаться, что настолько интенсивного периода в своей жизни, в плане реального и глубокого освоения новых навыков, у меня уже больше никогда не было.

Не хочу пренебречь другими учителями, которые сыграли важную роль в моём школьном образовании. Просто акцент в данной заметке не на них. Тем не менее, хочу особо отметить [[http://filippovsky.com/about][Григория Борисовича Филипповского]], [[https://www.rl.kiev.ua/news/pitannya-nashi-vidpovidi-vashi-irina-volodimirivna-mihajlik-13628/][Ирину Владимировну Михайлик]] и Александра Исааковича Апостолова. Кто знает, может в будущем я ещё напишу о них...

Но при всём при этом хочется отметить, что я /не/ разделяю полностью взглядов М. С. Например, я не разделяю его взгляда на роль математики в жизни его подопечных после окончания школы. В нашем классе была явная нацеленность на профессиональную математическую карьеру тех выпускников, что проявляли определённые успехи. Тот факт, что я в последних двух классах решил пойти учиться на физика, огорчило М.С. (не знаю, правда, насколько сильно), ведь физика считалась предметом второсортным по сравнению с математикой. При этом, никакого отторжения или дискриминации я тогда на себе не почувствовал, в целом царила атмосфера свободы. Впрочем, я давно не имел подходящей возможности поговорить с М. С., а позиции людей могут меняться со временем. И для полноты картины, приведу одно из высказываний М. С., направленное к нам, ученикам: "Можете ставать потом кем угодно, хоть рецидивистом, но только профессионалом". Такую крайность я тоже не разделяю, да и сказана она была видимо для подчёркивания акцента, а не всеръёз.

В качестве заключения скажу, что школьная математика является идеальным полигоном для развития аналитических способностей, абстрактного, логического и критического аспектов мышления. Математические задачи обладают уникальным свойством: их можно полностью и строго решить, без привнесения дополнительных (произвольных или оправданных) предположений о структуре оперируемых объектов. (Я не касаюсь сейчас таких тонких вещей, как неполная строгость в доказательстве теорем евклидовой геометрии исходя из одних лишь 5 аксиом. Давайте не в этот раз. По-моему, уход в такие дебри всё равно ничего нового не даёт, а любопытные могут пролистать, например, [[https://math.ru/lib/files/pdf/shen/shen-rigor.pdf]["О математической строгости и школьном курсе математики"]].) Хотя устойчивый навык решения нестандартных задач требует неимоверного вложения времени и сил, при правильном подходе и подборе задач, при подходящем окружении единомышленников это делать чрезвычайно увлекательно. Игра стоит свеч, а плоды пожинаются потом всю жизнь, начиная уже с университетской скамьи. При этом, преувеличивать роль математики в полноценном развитии подростка не стоит, это даже чревато опасностями.

Много ещё чем хочется поделиться касательно роли математики за пределами самóй чистой математики. В частности, парадоксальным выводом о том, что математика -- самая /простая/ из наук (имею в виду тот объём, который входит в школьную и университетскую программу), хотя может быть и самая /трудная/ в освоении. (Да-да, "простой" и "лёгкий" не являются синонимами, смотрите видео, которое я упоминал вышe, [[https://www.infoq.com/presentations/Simple-Made-Easy/][Simple Made Easy]].) Есть ещё мысли о том, каким является оптимальный карьерный путь среднестатистического выпускника хорошего маткласса, и как необходимо перестроить программу технического образования в соответствии с этим. Это результаты размышлений, которые меня занимали и в период аспирантуры по теоретической физике, и в последние годы, когда я ушёл в мир программирования, цифровой электроники и прикладных математических алгоритмов.

К читателям: если какие-то из поднятых вопросов Вас заинтересовали и хочется более подробного обсуждения, пишите в комментариях ниже, возможно я напишу ещё несколько постов. А с моей стороны, хотелось бы услышать мнения моих одноклассников и других людей, которые (были) увлечены школьной математикой. Особенно ценно мнение, отличное от моего, только пожалуйста, конструктивное.

#+BEGIN_EXPORT html
<div class="fb-comments" data-href="https://tyomaiva.github.io/posts/yakir/" data-numposts="7" data-width=""></div>
#+END_EXPORT


** TODO To sort
   :PROPERTIES:
   :EXPORT_FILE_NAME: another-post
   :END:
 Odna iz prichin: nervnaja nagruzka (ne prosto spokojnoje reshenie zadach), dalshe -- nesistematichnost poiska reshenia => polnaja nepredskazuemost otnositelno ishoda reshenija zadachi. Posledneje osoznal uzhe namnogo pozhe.

Не математический, а ультраматематический. (10 академических часов в неделю, за исключением доп кружков, тренировочных олипиад?)

Сам Я был скорее среднячком. Никогда не проходил дальше золотой медали на городской олимпиаде. И это на фоне одноклассников, которые получали результаты на /международном/ уровне: Почему так произошло, можно говорить отдельно, но факт есть факт.

Но элегантность, которая иногда не лежит на поверхности, и от которой даже часто не бывает практической ценности (впрочем, это так только при поверхностном взгляде со стороны).

 Основной вывод -- там где матетматика работает -- это бомба, количественные результаты которые, по сути, нельзя получить без её методов, ... Для примера, приведу точность Стандартной Модели физики частиц. Но при этом математика остаётся инструментом ... Когда подобрана абстракция, отрезано как можно больше лишнего, так уж складывается (в физике только?), что непрерывные числа, и для количественной связи без математики не обойтись.

Физика - явления бесконечно сложные, даже замерзание льда (сколько видов льда?)

Если взять пример из программирования, то неучёт таких, казалось бы, экзотических ситуаций приводит к печально известным и тем не менее до сих пор часто встречающимся дефектам, как buffer overflow (когда элементы многократно добавляются в массив один за другим без учёта его конечного размера).

/не/ идеализирую М. С. По-моему, со стороны он выглядит как вполне обычный человек, со своими достоинствами и набором недостатков. Также я
